kind: pipeline
name: default
type: ssh

server:
  host: 120.79.54.59
  user: root
  ssh_key:
    from_secret: ssh_key

steps:
  - name: build
    image: openjdk:8-jdk-alpine
    commands:
      - chmod +x ./gradlew
      - ./gradlew clean build