kind: pipeline
name: default
type: ssh

server:
  host: yasinshaw.com
  user: root
  ssh_key:
    from_secret: ssh_key

steps:
  - name: test
    image: openjdk:8-jdk-alpine
    commands:
      - chmod +x ./gradlew
      - echo "hello"
      - ./gradlew clean