kind: pipeline
type: docker
name: build

steps:
  - name: test
    image: gradle:6.6.1-jdk11
    volumes:
      - name: gradle
        path: /home/gradle/.gradle
    commands:
      - gradle test --parallel --no-daemon
  - name: build
    image: gradle:6.6.1-jdk11
    volumes:
      - name: gradle
        path: /home/gradle/.gradle
    commands:
      - gradle :adapter:bootJar --parallel --no-daemon

  - name: build docker image
    image: plugins/docker
    settings:
      username: yasinshaw
      password:
        from_secret: docker_password
      repo: registry.cn-hangzhou.aliyuncs.com/yasinshaw/yasin_backend
      registry: registry.cn-hangzhou.aliyuncs.com
      mirror: https://mzayqkhl.mirror.aliyuncs.com
      tags: latest

volumes:
  - name: gradle
    host:
      path: /root/.gradle/


---
kind: pipeline
type: ssh
name: deploy

server:
  host: yasinshaw.com
  user: root
  ssh_key:
    from_secret: ssh_key

steps:
  - name: pull docker image
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - docker login --username=yasinshaw --password=$DOCKER_PASSWORD registry.cn-hangzhou.aliyuncs.com
      - docker pull registry.cn-hangzhou.aliyuncs.com/yasinshaw/yasin_backend:latest

  - name: remove old docker container
    failure: ignore
    commands:
      - docker rm -f -v yasin_backend

  - name: start docker container
    environment:
      JASYPT_ENCRYPTOR_PASSWORD:
        from_secret: jasypt_pwd
    commands:
      - docker run -d --name=yasin_backend --restart=always -p 9090:8080 -e JASYPT_ENCRYPTOR_PASSWORD=$JASYPT_ENCRYPTOR_PASSWORD registry.cn-hangzhou.aliyuncs.com/yasinshaw/yasin_backend:latest
depends_on:
  - build