kind: pipeline
name: default

steps:
  - name: test
    image: gradle:6.6.1-jdk11
    commands:
      - gradle test --no-daemon
  - name: build
    image: gradle:6.6.1-jdk11
    commands:
      - gradle build
