kind: pipeline
name: default

steps:
  - name: test
    image: openjdk:11.0.9.1-jdk-buster
    commands:
      - chmod +x ./gradlew
      - ./gradlew test --no-daemon
  - name: build
    image: openjdk:11.0.9.1-jdk-buster
    commands:
      - chmod +x ./gradlew
      - ./gradlew build --no-daemon
